server:
    port: 8081
spring:
  session:
    timeout: 6H
  servlet:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb
  datasource:
    sys:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=HES;
        username: sa
        password: 2333
    scm:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=AIS20090112170128;
        username: sa
        password: 2333
    thymeleaf:
        cache: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

pagehelper:
    helperDialect: sqlserver
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
logging:
  level:
    com.hennro.hes.module.scm.core.mapper: trace


